import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomTabNav from "./components/BottomTabNav";
import NicknameOnboarding from "./components/NicknameOnboarding";
import SplashScreen from "./components/SplashScreen";
import KakaoSdk from "./components/KakaoSdk";
import { createAdminClient } from "@/lib/supabase/admin";

async function getRandomAwardPhoto() {
  const supabase = createAdminClient();

  const { count, error: countError } = await supabase
    .from("travel_award_photos")
    .select("*", { count: "exact", head: true });

  if (countError || !count) {
    if (countError) console.error("전국 여행 사진관 count 조회 오류:", countError.message);
    return null;
  }

  const randomOffset = Math.floor(Math.random() * count);

  const { data, error } = await supabase
    .from("travel_award_photos")
    .select("org_image, ko_title, ko_cman_nm, film_day")
    .range(randomOffset, randomOffset)
    .single();

  if (error || !data) {
    if (error) console.error("전국 여행 사진관 랜덤 조회 오류:", error.message);
    return null;
  }

  return {
    url: data.org_image as string,
    title: data.ko_title as string,
    photographer: data.ko_cman_nm as string,
    filmDay: data.film_day as string,
  };
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const backgroundPhoto = await getRandomAwardPhoto();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <div className="flex-1 pb-20">{children}</div>
        <NicknameOnboarding />
        <BottomTabNav />
        <SplashScreen backgroundPhoto={backgroundPhoto} />
        <KakaoSdk />
      </body>
    </html>
  );
}
